Feature/dcg 142 sytemuser systemrole
Cesardf1/projeto-comrade-front pull request #2
Opened 2022-10-03 12:30 UTC by Cesardf1

2022-10-03 13:07 UTC, pedroLFaria commented
Ignorar todos os arquivos em .vs e deletar eles da branch.

2022-10-05 14:08 UTC, Cesardf1 commented
@pedroLFaria @Cesardf1
.vs adicionado ao git ignore e
 conteudo do .vs deletado.

2022-10-05 18:10 UTC, pedroLFaria requested changes

2022-10-05 18:10 UTC, pedroLFaria commented on src/app/core/usecases/system-permission/post-bank.usecase.ts
> +export class PostSystemPermissionUsecase
Nome do arquivo está post-bank, diferente da classe

2022-10-05 18:10 UTC, pedroLFaria commented on src/app/core/usecases/system-role/post-bank.usecase.ts
> +export class PostSystemRoleUsecase implements UseCase<SystemRoleModel, SystemRoleModel> {
Outro arquivo com nome post-bank, isso está certo?

2022-10-05 18:10 UTC, pedroLFaria commented on src/app/data/lookup-repository/cargo-sistema-lookup-web.repository.ts
> +export class SystemRoleLookupWebRepository extends SystemRoleLookupRepository {
Nome do arquivo e nome da classe estão bem diferentes e idiomas diferentes, está certo isso?

2022-10-05 18:10 UTC, pedroLFaria commented on src/app/data/lookup-repository/permissao-sistema-lookup-web.repository.ts
> +export class SystemPermissionLookupWebRepository extends SystemPermissionLookupRepository {
Nome da classe e arquivo estão bem diferentes, pode checar isso?

2022-10-05 18:10 UTC, pedroLFaria commented on src/app/view/pages/system-user-role/system-user-role.component.ts
> +    for (j = 0; j < this.selectedSystemUser.systemRoles.length; j++) {
Verificar outros tipos de for que temos no JS, como for in e for on

2022-10-05 18:10 UTC, pedroLFaria commented on src/app/core/usecases/system-permission/post-bank.usecase.ts
> +export class PostSystemPermissionUsecase
Nome da classe diferente do nome do arquivo

2022-10-06 02:28 UTC, pedroLFaria requested changes

2022-10-06 02:28 UTC, pedroLFaria commented on src/app/view/pages/system-user-role/system-user-role.component.ts
> +    for (i = 0; i < this.selectedSystemUser.systemRoles.length; i++) {
Ver os outros tipos de for no JS ou as funções que iteram tbm.

2022-10-06 02:28 UTC, pedroLFaria commented on src/app/view/pages/system-user-role/system-user-role.component.ts
> +    } else {
Isso é um else vazio?

2022-10-07 23:13 UTC, pedroLFaria approved these changes

2022-10-10 18:14 UTC, pedroLFaria approved these changes

2022-10-10 18:23 UTC, merged